name: flutter_network_inspector
description: This package allows you to monitor network calls made with Dart’s http package. Track all your HTTP requests easily without using third-party libraries.
version: 2.0.0
homepage: https://github.com/flutterthemer/flutter_network_inspector

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  connectivity_plus: ^6.0.5
  dio: ^5.7.0
  flutter:
    sdk: flutter
  
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

linter:
  rules:
    - public_member_api_docs