name: flutter_network_inspector
description: This package helps you to monitor networks calls done using the http package with in the app. if you are using the dart's http package and not using any third party packages, you an use this library to track all your http requests.
version: 0.0.8
homepage: https://dart.dev/

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
